In [7]:
#Collection of documents (corpus)

review_1 = "The Glider II is a great soccer ball"
review_2 = "What a bad soccer ball"
review_3 = "I am happy with The glider"

In [8]:
docs = [review_1, review_2, review_3]
docs

['The Glider II is a great soccer ball',
 'What a bad soccer ball',
 'I am happy with The glider']

In [9]:
#Gather the set of all unique terms

unique_terms = {term for doc in docs for term in doc.split()}
unique_terms

{'Glider',
 'I',
 'II',
 'The',
 'What',
 'a',
 'am',
 'bad',
 'ball',
 'glider',
 'great',
 'happy',
 'is',
 'soccer',
 'with'}

In [10]:
#Construct a term-document matrix
#here as a Python dictionary for ease of interpretabiliy

doc_term_matrix = {}

for term in unique_terms:
    doc_term_matrix[term] = []
    
    for doc in docs:
        if term in doc:
            doc_term_matrix[term].append(1)
        else: doc_term_matrix[term].append(0)
            
doc_term_matrix
            

{'bad': [0, 1, 0],
 'great': [1, 0, 0],
 'is': [1, 0, 0],
 'II': [1, 0, 0],
 'soccer': [1, 1, 0],
 'ball': [1, 1, 0],
 'am': [0, 0, 1],
 'a': [1, 1, 1],
 'The': [1, 0, 1],
 'happy': [0, 0, 1],
 'glider': [0, 0, 1],
 'with': [0, 0, 1],
 'I': [1, 0, 1],
 'What': [0, 1, 0],
 'Glider': [1, 0, 0]}

In [14]:
# The query to find all documents containing "Glider" and "soccer"
# Is just a bitwise AND:

import numpy as np

docs_array = np.array(docs, dtype='object')

v1=np.array(doc_term_matrix['Glider'])
v2=np.array(doc_term_matrix['soccer'])

print(v1)
print(v2)
print('........')
v3=v1 & v2
print(v3)

[1 0 0]
[1 1 0]
........
[1 0 0]


In [15]:
# We can now get the matching documents from our corpus with result
[doc for doc in v3 * docs_array if doc]

['The Glider II is a great soccer ball']

In [17]:
v1 = np.array(doc_term_matrix['a'])
v2 = np.array(doc_term_matrix['ball'])

print(v1)
print(v2)
print('........')
v3=v1 & v2
print(v3)


[1 1 1]
[1 1 0]
........
[1 1 0]


In [18]:
[doc for doc in v3 * docs_array if doc]

['The Glider II is a great soccer ball', 'What a bad soccer ball']

In [19]:
# Bitwise OR to constuct 'this' of 'that' queries.

In [21]:
v1 = np.array(doc_term_matrix['great'])
v2 = np.array(doc_term_matrix['bad'])

print(v1)
print(v2)
print('........')
v3=v1 | v2
print(v3)


[1 0 0]
[0 1 0]
........
[1 1 0]


In [22]:
[doc for doc in v3 * docs_array if doc]

['The Glider II is a great soccer ball', 'What a bad soccer ball']